# TAREA 1

In [ ]:
# Crea un bucle para obtener el promedio de todos los elementos que se encuentran en las siguientes listas
# Crea un bucle que divida en 3 listas del mismo tamaño a los elementos de las listas anteriores ordenados de menor a mayor.
# Crea una código que reciba del usuario nueve elementos de una matriz cuadrada de 3x3 y que retorne el determinante de la matriz.
# Crea un código que reciba una cadena de caracteres y arroje la respuesta de si es un estado ó una capital del país.
# Pide al usuario dos listas de números reales (misma longitud) y calcula su producto escalar usando un bucle for.
# Utiliza un bucle while True para pedir números al usuario y agregarlos a una lista. Cuando la suma total de los elementos sea mayor a 100, el programa debe detenerse y mostrar la lista y la suma final.
# Crea una lista vacía y presenta al usuario un menú como este dentro de un while True:

In [1]:
L1=[7.2,7.8,6.8,8.0,None,'8.2',5.6,8.2,7.7,7.5,None,5.8]
L2=['6.8',None,6.8,6.1,7.9,9.4,None]
L3=[8.5,'9.0',None,7.7]

In [5]:

datos_validos = []
for lista in [L1, L2, L3]:
    for elemento in lista:
        if elemento is None:
            continue
        try:
            num = float(elemento)
            datos_validos.append(num)
        except (TypeError, ValueError):
            continue

promedio = sum(datos_validos) / len(datos_validos) if datos_validos else 0
print(f"Promedio: {promedio:.2f}")

Promedio: 7.50


In [12]:

datos_validos.sort()

n = len(datos_validos) // 3
sublistas = [datos_validos[i*n : (i+1)*n] for i in range(3)]

print("Sublistas ya ordenadas")
for i, sublista in enumerate(sublistas, 1):
    print(f"Sublista {i}: {sublista}")

Sublistas ordenadas
Sublista 1: [5.6, 5.8, 6.1, 6.8, 6.8, 6.8]
Sublista 2: [7.2, 7.5, 7.7, 7.7, 7.8, 7.9]
Sublista 3: [8.0, 8.2, 8.2, 8.5, 9.0, 9.4]


In [22]:
import numpy as np

def determinante_numpy():
    print("Ingrese los 9 elementos de la matriz 3x3 (fila por fila):")
    elementos = [float(input(f"Elemento [{i//3 + 1}][{i%3 + 1}]: ")) for i in range(9)]
    matriz = np.array(elementos).reshape(3, 3)

    print("\nMatriz ingresada:")
    print(matriz)

    det = np.linalg.det(matriz)
    return int(det) if det.is_integer() else det

# Ejemplo de uso
det = determinante_numpy()
print(f"\nEl determinante de la matriz es: {det}")

Ingrese los 9 elementos de la matriz 3x3 (fila por fila):
Elemento [1][1]: 1 
Elemento [1][2]: 2
Elemento [1][3]: 3
Elemento [2][1]: 1
Elemento [2][2]: 1
Elemento [2][3]: 0
Elemento [3][1]: 0
Elemento [3][2]: 0
Elemento [3][3]: 1

Matriz ingresada:
[[1. 2. 3.]
 [1. 1. 0.]
 [0. 0. 1.]]

El determinante de la matriz es: -1


In [17]:
estados_capitales = {
    "Aguascalientes": "Aguascalientes",
    "Baja California": "Mexicali",
    "Baja California Sur": "La Paz",
    "Campeche": "San Francisco de Campeche",
    "Chiapas": "Tuxtla Gutiérrez",
    "Chihuahua": "Chihuahua",
    "Coahuila": "Saltillo",
    "Colima": "Colima",
    "Durango": "Durango",
    "Guanajuato": "Guanajuato",
    "Guerrero": "Chilpancingo de los Bravo",
    "Hidalgo": "Pachuca de Soto",
    "Jalisco": "Guadalajara",

    "Michoacán": "Morelia",
    "Morelos": "Cuernavaca",
    "Nayarit": "Tepic",
    "Nuevo León": "Monterrey",
    "Oaxaca": "Oaxaca de Juárez",
    "Puebla": "Puebla de Zaragoza",
    "Querétaro": "Santiago de Querétaro",
    "Quintana Roo": "Chetumal",
    "San Luis Potosí": "San Luis Potosí",
    "Sinaloa": "Culiacán Rosales",
    "Sonora": "Hermosillo",
    "Tabasco": "Villahermosa",
    "Tamaulipas": "Ciudad Victoria",
    "Tlaxcala": "Tlaxcala de Xicohténcatl",
    "Veracruz": "Xalapa-Enríquez",
}

def verificar_estado_o_capital():
    entrada = input("Ingrese un estado o capital de México: ").strip().title()

    if entrada in estados_capitales:
        print(f"'{entrada}' es un estado de México.")
    elif entrada in estados_capitales.values():
        estado = [estado for estado, capital in estados_capitales.items() if capital == entrada][0]
        print(f"'{entrada}' es la capital de {estado}.")
    else:
        print(f"'{entrada}' no es ni un estado ni una capital de México.")


verificar_estado_o_capital()

Ingrese un estado o capital de México: chiapas
'Chiapas' es un estado de México.


In [19]:
import numpy as np

# Pedir datos al usuario
print("Ingresa los números de la primera lista (separados por espacios):")
lista1 = np.array([float(x) for x in input().split()])

print("Ingresa los números de la segunda lista (separados por espacios):")
lista2 = np.array([float(x) for x in input().split()])

# Verificar tamaño
if len(lista1) != len(lista2):
    print("Error: Las listas deben tener el mismo tamaño")
else:
    # Calcular producto escalar y mostrar sin formato decimal fijo
    producto = np.sum(lista1 * lista2)
    print("El producto escalar es:", producto)

Ingresa los números de la primera lista (separados por espacios):
1 2 3 
Ingresa los números de la segunda lista (separados por espacios):
1 2 3
El producto escalar es: 14.0


In [23]:
numeros = []
suma_total = 0

print("Ingrese números uno por uno.")

while True:
    try:
        numero = float(input("Ingrese un número: "))

        numeros.append(numero)

        suma_total += numero

        if suma_total > 100:
            print("\La suma ha superado 100")
            print(f"Lista de números ingresados: {numeros}")
            print(f"Suma total: {suma_total}")
            break

    except ValueError:
        print("Error: Por favor ingrese un número válido.")

Ingrese números uno por uno. El programa terminará cuando la suma supere 100.
Ingrese un número: 2
Ingrese un número: 22
Ingrese un número: 44
Ingrese un número: 55

¡La suma ha superado 100!
Lista de números ingresados: [2.0, 22.0, 44.0, 55.0]
Suma total: 123.0


Crea una lista vacía y presenta al usuario un menú como este dentro de un while True:

El usuario debe poder ejecutar varias opciones hasta que elija salir.


In [ ]:
lista = []

while True:
    print("\nMenú:")
    print("1. Agregar número")
    print("2. Mostrar lista")
    print("3. Salir")

    opcion = input("Seleccione una opción: ")

In [25]:
lista = []

while True:
    print("n\1. Agregar número")
    print("2. Ver lista")
    print("3. Salir")

    op = input("Opción: ")

    if op == "1":
        num = float(input("Número: "))
        lista.append(num)
    elif op == "2":
        print("Lista:", lista)
    elif op == "3":
        break
    else:
        print("Opción incorrecta")

. Agregar número
2. Ver lista
3. Salir
Opción: 1
Número: 1
. Agregar número
2. Ver lista
3. Salir
Opción: 3
